namespace A2SEVEN.UnitTests.Shared.Constants;

public static class TokenConstants
{
    public const string JwtTokenTest = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2NzY2MzA3MTYsImV4cCI6MTcwODE2NjcxNiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoibG9naW4iLCJHaXZlbk5hbWUiOiJMb2dpbiJ9.kENlR-MCskBWV9Tp5B4VA77PEfAv3vt6LfsbER2WOs4";
    public const string RefreshTokenTest = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2NzY2MzA3MTYsImV4cCI6MTcwODE2NjcxNiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoibG9naW4iLCJHaXZlbk5hbWUiOiJMb2dpbiJ9.kENlR-MCskBWV9Tp5B4VA77PEfAv3vt6LfsbER2WOs4";
    public const string NewJwtTokenTest = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2NzY2MzA3MTYsImV4cCI6MTcwODE2NzAxNiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoibG9naW4iLCJHaXZlbk5hbWUiOiJMb2dpbiJ9.Ht_Bcj-vgcpafoa0RUkkh_IQVKivx7AzLq2HqKNagGs";
    public const string ExpiredTokenTest = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2NzY2MzA3MTYsImV4cCI6MTY3NjYzMTAxNiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoibG9naW4iLCJHaXZlbk5hbWUiOiJMb2dpbiJ9.GROd-k6pW4pIIUFAr_jhegcmpSckYD0nzhe0RRKgcSg";
}