version: "3"
services:
  backend:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    depends_on:
      - "postgres"
    ports:
      - ${API_PORT}:80
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=${PG_PORT};Database=${PG_DB};Username=${PG_USER};Password=${PG_PWD};
    restart: unless-stopped
    env_file: .env

  postgres:
    image: postgres
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${PG_DB}
    restart: unless-stopped
    ports:
      - ${PG_PORT}:5432
    env_file: .env
