version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
